# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'FlexSpace' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FlexSpace
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'FlexSpaceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
